name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 2.0.1
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  collection: ^1.15.0

flutter: